spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://SQL6031.site4now.net;databaseName=db_abf652_gss;encrypt=false;trustServerCertificate=true
spring.datasource.username=db_abf652_gss_admin
spring.datasource.password=AJDINAJDIN123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

