spring.application.name=demo

# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-round-rice-agqykta3-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mJ7SNVZ1wRIq
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT konfiguracija
jwt.secret=bT5IXolVRFTbuj06wq2ZP/ez5I33xHVvbh2JpyS1N98qVT0qCS8w8606DoI9bHkC2mg4M27XFSK7BQkXZDhBDA==
jwt.expiration=86400000

# 🔁 backup za slučaj da neka klasa traži app.jwt.*
app.jwt.secret=${jwt.secret}
app.jwt.expiration=${jwt.expiration}

app.jwt.expires-in-seconds=86400

server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG
